/* jshint ignore:start,-W101 */
// THIS FILE IS ADDED HERE TO ADD TESTS
var allowedHostAPIOrigins = '$!{store_cardinal_allowed_host_api_origins}'.split(',');
var storeLanguage = '${drog_store_language}';
var _localizations = {
  'drog.storeMaintenance.header' : '${drog_cardinal_storeMaintenance_header}',
  'drog.storeMaintenance.displayValue' : '${drog_cardinal_storeMaintenance_displayValue}',
  'drog.error.sessionexpire.alert' : '${drog_cardinal_error_sessionexpire_alert}',
  'drog.text.back.to.store' : '${drog_cardinal_text_back_to_store}',
  'drog.terms.not.accepted' : '${drog_cardinal_terms_not_accepted}',
  'drog.error.validation.alert' : '${drog_cardinal_error_validation_alert}',
  'drog.transaction.progress.header' : '${drog_cardinal_transaction_progress_header}',
  'drog.you.have.successfully.cancelled.your.transaction' : '${drog_cardinal_you_have_successfully_cancelled_your_transaction}',
  'drog.please.try.again.by.using.a.different.payment.method' : '${drog_cardinal_please_try_again_by_using_a_different_payment_method}',
  'drog.payment.externalinfo.message': '${drog_cardinal_payment_externalinfo_message}',
  'drog.default.error': '${drog_cardinal_default_error}',
  'drog.text.credit.card.ending' : '${drog_cardinal_text_credit_card_ending}',
  'drog.text.edit': '${drog_cardinal_text_edit}',
  'drog.back.to.store.full.url' : '${drog_back_to_store_full_url}',
  'drog.back.to.store.purchase.finished.full.url' : '${drog_back_to_store_purchase_finished_full_url}',
  'drog.text.offer.discount.was' : '${drog_cardinal_text_offer_discount_was}',
  'drog.text.offer.discount.save' : '${drog_cardinal_text_offer_discount_save}',
  'drog.text.offer.countdown.ends.in' : '${drog_cardinal_text_offer_countdown_ends_in}',
  'drog.text.offer.bonus' : '${drog_cardinal_text_offer_bonus}',
  'drog.link.cardinal.faq.url' : '${drog_link_cardinal_faq_url}',
  'drog.link.cardinal.tos.url' : '${drog_link_cardinal_tos_url}',
  'drog.paymentInfo.external.redirect' : "${drog_cardinal_paymentInfo_external_redirect}",
  'drog.confirm.payment.price.tax' : '${drog_cardinal_confirm_payment_price_tax}',
  'drog.confirm.payment.price.sales.taxes' : '${drog_cardinal_confirm_payment_price_sales_taxes}',
  'drog.payment.authorization.failed' : '${drog_cardinal_payment_authorization_failed}',
  'drog.text.no.offers.available' : '${drog_cardinal_text_no_offers_available}',
  'drog.text.confirm.tax' : '${drog_cardinal_text_confirm_tax}',
  'drog.transaction.authorize.message' : '${drog_cardinal_transaction_authorize_message}',
  'drog.cardinal.transaction.failure.header' : '${drog_cardinal_transaction_failure_header}',
  'drog.text.dialog.okay' : '${drog_cardinal_text_dialog_okay}',
  'drog.payment.followup.message' : '${drog_cardinal_payment_followup_message}',
  'drog.store.new.paypal.billing.agreement' : '${drog_cardinal_store_new_paypal_billing_agreement}',
  'drog.store.make.one.time.paypal.purchase' : '${drog_cardinal_store_make_one_time_paypal_purchase}',
  'drog.store.use.another.payment.method' : '${drog_cardinal_store_use_another_payment_method}',
  'drog.cardinal.transaction.authorize.payment' : '${drog_cardinal_transaction_authorize_payment}',
  'drog.cardinal.overlay.header.default' : '${drog_cardinal_overlay_header_default}',
  'drog.cardinal.overlay.header.enter.store' : '${drog_cardinal_overlay_header_enter_store}',
  'drog.cardinal.overlay.header.country.updating' : '${drog_cardinal_overlay_header_country_updating}',
  'drog.cardinal.overlay.header.to.review.order' : '${drog_cardinal_overlay_header_to_review_order}',
  'drog.cardinal.overlay.content.enter.store' : '${drog_cardinal_overlay_content_enter_store}',
  'drog.cardinal.overlay.content.country.updating' : '${drog_cardinal_overlay_content_country_updating}',
  'drog.cardinal.overlay.content.to.review.order' : '${drog_cardinal_overlay_content_to_review_order}',
  'drog.sepa.mandate.please.agreeterms' : '${drog_cardinal_sepa_mandate_please_agreeterms}',
  'drog.sepa.direct.debit.mandate.type.recurring' : '${drog_cardinal_sepa_direct_debit_mandate_type_recurring}',
  'drog.sepa.mandate.description.sign1.recurrent' : '${drog_cardinal_sepa_mandate_description_sign1_recurrent}',
  'drog.sepa.mandate.description.sign2.recurrent' : '${drog_cardinal_sepa_mandate_description_sign2_recurrent}',
  'drog.sepa.mandate.description.rights.recurrent' : '${drog_cardinal_sepa_mandate_description_rights_recurrent}',
  'drog.sepa.direct.debit.mandate.type.one.off' : '${drog_cardinal_sepa_direct_debit_mandate_type_one_off}',
  'drog.sepa.mandate.description.sign1.one.off' : '${drog_cardinal_sepa_mandate_description_sign1_one_off}',
  'drog.sepa.mandate.description.sign2.one.off' : '${drog_cardinal_sepa_mandate_description_sign2_one_off}',
  'drog.sepa.mandate.description.rights.one.off' : '${drog_cardinal_sepa_mandate_description_rights_one_off}',
  'drog.cardinal.please.enter.a.valid.email.address' : '${drog_cardinal_please_enter_a_valid_email_address}',
  'drog.cardinal.text.delete.stored.payment.form': '${drog_cardinal_text_delete_stored_payment_form}',
  'drog.cardinal.text.creditcard.delete': '${drog_cardinal_text_creditcard_delete}'
};